name: quiz05
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - annotated-doc=0.0.4=pyhcf101f3_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.0=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - aws-c-auth=0.9.1=h8818502_7
  - aws-c-cal=0.9.10=hca30140_1
  - aws-c-common=0.12.5=hc919400_1
  - aws-c-compression=0.3.1=h61d5560_8
  - aws-c-event-stream=0.5.6=h18584fc_6
  - aws-c-http=0.10.7=hcd69b29_4
  - aws-c-io=0.23.3=h9710c81_3
  - aws-c-mqtt=0.13.3=ha255ef3_10
  - aws-c-s3=0.10.1=hd860258_2
  - aws-c-sdkutils=0.2.4=h61d5560_3
  - aws-checksums=0.2.7=h61d5560_4
  - aws-crt-cpp=0.35.2=h5596a46_4
  - aws-sdk-cpp=1.11.606=h95becb6_7
  - azure-core-cpp=1.16.1=h88fedcc_0
  - azure-identity-cpp=1.13.2=h853621b_1
  - azure-storage-blobs-cpp=12.15.0=h10d327b_1
  - azure-storage-common-cpp=12.11.0=h7e4aa5d_1
  - azure-storage-files-datalake-cpp=12.13.0=hb288d13_1
  - bokeh=3.8.1=pyhd8ed1ab_0
  - brotli-python=1.2.0=py310h6123dab_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310hf5b66c1_1
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310h7f4e7e6_0
  - cytoolz=1.1.0=py310hfe3a0ae_1
  - dask=2024.4.1=pyhd8ed1ab_0
  - dask-core=2024.4.1=pyhd8ed1ab_0
  - dask-expr=1.0.11=pyhd8ed1ab_0
  - dask-sql=2024.5.0=py310h8fb3fad_0
  - debugpy=1.8.17=py310h7b404bc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distributed=2024.4.1=pyhd8ed1ab_0
  - dnspython=2.8.0=pyhcf101f3_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fastapi=0.123.5=h6c771bf_0
  - fastapi-cli=0.0.16=pyhcf101f3_1
  - fastapi-core=0.123.5=pyhcf101f3_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - gflags=2.2.2=hf9b8971_1005
  - glog=0.7.1=heb240a5_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py310hfe3a0ae_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - ipykernel=6.29.3=pyh3cd1d5f_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libarrow=22.0.0=h4a3aeba_4_cpu
  - libarrow-acero=22.0.0=hc317990_4_cpu
  - libarrow-compute=22.0.0=h75845d1_4_cpu
  - libarrow-dataset=22.0.0=hc317990_4_cpu
  - libarrow-substrait=22.0.0=h144af7f_4_cpu
  - libblas=3.11.0=3_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=3_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=21.1.7=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_14
  - libgfortran=15.2.0=h07b0088_14
  - libgfortran5=15.2.0=hdae7583_14
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=3_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=22.0.0=h0ac143b_4_cpu
  - libpng=1.6.51=hfab5511_0
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.11.05=h91c62da_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.1=h9a5124b_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h4030677_1
  - libutf8proc=2.11.2=hd2415e0_0
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=hba2cd1d_0
  - libxml2-16=2.15.1=h8eac4d7_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.7=h4a912ad_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py310h36fcd3f_0
  - lz4-c=1.10.0=h286801f_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310hf4fd40f_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py310h0e897d2_1
  - narwhals=2.13.0=pyhcf101f3_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h248ca61_1
  - numpy=1.26.4=py310hd45542a_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - orc=2.2.1=h4fd0076_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.1=py310h401b61c_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.0.0=py310hce4cfee_2
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py310hf151d32_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=22.0.0=py310hb6292c7_0
  - pyarrow-core=22.0.0=py310h6cc04f2_0_cpu
  - pyarrow-hotfix=0.7=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py310hf3301a5_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=hcd7f573_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310hf4fd40f_0
  - pyzmq=27.1.0=py310hc4a7dca_0
  - re2=2025.11.05=h64b956e_0
  - readline=8.2=h1d1bf99_2
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.17.0=pyhcf101f3_0
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - starlette=0.50.0=pyhfdc7a7d_0
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tblib=3.2.2=pyhcf101f3_0
  - tk=8.6.13=h892fb3f_3
  - tomli=2.3.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.2=py310hfe3a0ae_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.20.0=pyhefaf540_1
  - typer-slim=0.20.0=pyhcf101f3_1
  - typer-slim-standard=0.20.0=h4daf872_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - tzlocal=5.3.1=pyh8f84b5b_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - uvicorn=0.38.0=pyh31011fe_0
  - uvicorn-standard=0.38.0=h31011fe_0
  - uvloop=0.22.1=py310hfe3a0ae_1
  - watchfiles=1.1.1=py310h53169e7_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - websockets=15.0.1=py310h2ee35b4_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.3.2=h248ca61_0
  - zstandard=0.25.0=py310hf151d32_1
  - zstd=1.5.7=hbf9d68e_6
prefix: /opt/anaconda3/envs/quiz05
